name: CI-CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    
jobs:
  build-browser:
    name: ${{ matrix.os }} - browser target (Docker image build)
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [12]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Build Browser Target
        if: ${{ matrix.target }} == "browser"
        shell: bash
        run: |
          cd browser
          docker build --no-cache .