name: browser

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-browser:
    name: ${{ matrix.os }} - (Docker image build)
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [12]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Build Browser Target
        shell: bash
        run: |
          cd browser
          docker build --no-cache . --tag ${{secrets.DOCKER_USER}}/selene-ide-browser:latest

      - name: Docker Login
        if: ${{ github.event_name == 'push' }}
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Docker Deploy
        if: ${{ github.event_name == 'push' }}
        run: docker push ${{secrets.DOCKER_USER}}/selene-ide-browser:latest
